version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Setup testing environment
          command: |
            pip install coverage --user
            pip install codecov --user
            export PATH=/path/to/foo/bin:$PATH
      - run:
          name: Run Tests
          command: |
            coverage run -m unittest
            coverage report
            coverage html
            codecov
      - store_artifacts:
          path: htmlcov